In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
df = pd.read_csv(prefix + 'yellow_tripdata_2021-01.csv.gz', nrows=100)

# display the first rows
df.head()

# check the data types
df.dtypes

# check the shape
df.shape

(100, 18)

In [3]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [4]:
df.dtypes

VendorID                   int64
tpep_pickup_datetime         str
tpep_dropoff_datetime        str
passenger_count            int64
trip_distance            float64
RatecodeID                 int64
store_and_fwd_flag           str
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [6]:
len(df)

100

In [7]:
df.shape

(100, 18)

In [8]:
df.describe()

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
count,100.000000,100.000000,100.0000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000,100.000000,100.000000,100.000,100.000000,100.000000
mean,1.650000,1.570000,3.5610,1.020000,168.410000,158.360000,1.430000,12.987000,1.095000,0.495,2.096600,0.183600,0.297,18.679200,2.125000
std,0.479372,1.007597,3.8553,0.140705,67.708987,74.842396,0.590412,10.509915,1.077068,0.050,2.650679,1.049253,0.030,12.236805,0.897176
min,1.000000,0.000000,0.0000,1.000000,4.000000,3.000000,1.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000,0.000000,0.000000
25%,1.000000,1.000000,1.1675,1.000000,132.000000,89.250000,1.000000,6.500000,0.500000,0.500,0.000000,0.000000,0.300,11.160000,2.500000
50%,2.000000,1.000000,2.2100,1.000000,151.000000,151.000000,1.000000,9.500000,0.500000,0.500,1.860000,0.000000,0.300,14.550000,2.500000
75%,2.000000,2.000000,4.0925,1.000000,238.000000,233.250000,2.000000,16.500000,1.000000,0.500,2.805000,0.000000,0.300,23.320000,2.500000
max,2.000000,5.000000,19.1000,2.000000,264.000000,264.000000,4.000000,52.000000,3.000000,0.500,12.250000,6.120000,0.300,73.670000,2.500000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               100 non-null    int64
 1   tpep_pickup_datetime   100 non-null    str
 2   tpep_dropoff_datetime  100 non-null    str
 3   passenger_count        100 non-null    int64
 4   trip_distance          100 non-null    float64
 5   RatecodeID             100 non-null    int64
 6   store_and_fwd_flag     100 non-null    str
 7   PULocationID           100 non-null    int64
 8   DOLocationID           100 non-null    int64
 9   payment_type           100 non-null    int64
 10  fare_amount            100 non-null    float64
 11  extra                  100 non-null    float64
 12  mta_tax                100 non-null    float64
 13  tip_amount             100 non-null    float64
 14  tolls_amount           100 non-null    float64
 15  improvement_surcharge  100 non-null    float64
 16  total_amount           100 non-null    float64
 17  congestion_surcharge   100 non-null    float64
dtypes: float64(9), int64(6), str(3)
memory usage: 18.0 KB

In [10]:
df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
dtype: int64